os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.2

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install vapor/tap/vapor  ; fi

script:
  - swift build

notifications:
  email:
    on_success: never
    on_failure: change
